from django.urls import path

from main.views import (
    create_project_ajax,
    show_main,
    show_experience,
    show_gallery,
    show_highlights,
    create_project,
    update_project,
    show_projects,
    get_projects_json,
    delete_project,
    create_highlight,
    toggle_star,
    update_highlight,
    delete_highlight,
    get_highlights_json,
    create_experience,
    update_experience,
    delete_experience,
    get_experiences_json,
    create_gallery_item,
    create_gallery_item_ajax,
    update_gallery_item,
    delete_gallery_item,
    get_gallery_items_json,
    toggle_gallery_star,
    register,
    login_user,
    logout_user,
)

app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("experience/", show_experience, name="show_experience"),
    path("experience/add/", create_experience, name="create_experience"),
    path("experience/<uuid:experience_id>/edit/", update_experience, name="update_experience"),
    path("experience/<uuid:experience_id>/delete/", delete_experience, name="delete_experience"),
    path("api/experience/", get_experiences_json, name="get_experiences_json"),
    path("highlights/", show_highlights, name="show_highlights"),
    path("highlights/add/", create_highlight, name="create_highlight"),
    path("highlights/<int:highlight_id>/edit/", update_highlight, name="update_highlight"),
    path("highlights/<int:highlight_id>/delete/", delete_highlight, name="delete_highlight"),
    path("api/highlights/", get_highlights_json, name="get_highlights_json"),
    path("gallery/", show_gallery, name="show_gallery"),
    path("gallery/add/", create_gallery_item, name="create_gallery_item"),
    path("gallery/<int:item_id>/edit/", update_gallery_item, name="update_gallery_item"),
    path("gallery/<int:item_id>/delete/", delete_gallery_item, name="delete_gallery_item"),
    path("gallery/<int:item_id>/star/", toggle_gallery_star, name="toggle_gallery_star"),
    path("api/gallery/", get_gallery_items_json, name="get_gallery_items_json"),
    path("gallery/add-ajax/", create_gallery_item_ajax, name="create_gallery_item_ajax"),
    path("projects/add/", create_project, name="create_project"),
    path("projects/", show_projects,name="show_projects"),
    path("api/projects/", get_projects_json, name="get_projects_json"),
    path("projects/<uuid:project_id>/edit/", update_project, name="update_project"),
    path("projects/<uuid:project_id>/delete/",delete_project,name="delete_project"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path(
    "projects/<uuid:project_id>/star/",
    toggle_star,
    name="toggle_star",
    ),
    path("projects/add-ajax/", create_project_ajax, name="create_project_ajax"),
]
