# Generated by Django 5.2.17 on 2026-09-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='thumbnail',
            field=models.CharField(blank=True, null=True),
        ),
    ]
